/*
 Navicat Premium Data Transfer

 Source Server         : 马钢
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : oracle1.test.baiwang-inner.com:1521
 Source Schema         : MGJT

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 16/10/2018 15:28:54
*/


-- ----------------------------
-- Table structure for T_SCM_VAT_MAIN_EXTEND
-- ----------------------------
DROP TABLE "MGJT"."T_SCM_VAT_MAIN_EXTEND";
CREATE TABLE "MGJT"."T_SCM_VAT_MAIN_EXTEND" (
  "ID" NUMBER NOT NULL ,
  "ACCOUNT_TIME" DATE ,
  "VOUCHER_NUM" VARCHAR2(32 BYTE) ,
  "INV_KIND" VARCHAR2(40 BYTE) ,
  "INV_NUM" VARCHAR2(40 BYTE) ,
  "SYS_COMPANY_CODE" VARCHAR2(40 BYTE) ,
  "STATUS" VARCHAR2(20 BYTE) ,
  "UPDATE_TIME" DATE ,
  "TAX_NO" VARCHAR2(40 BYTE) ,
  "UPDATE_TYPE" VARCHAR2(40 BYTE) ,
  "ACCOUNTTING_NO" VARCHAR2(40 BYTE) ,
  "ACCOUNT_STATUS" VARCHAR2(40 BYTE) ,
  "AMOUNT_USE" NUMBER ,
  "TAX_USE" NUMBER ,
  "APPLY_TIME" DATE ,
  "APPLY_NAME" VARCHAR2(40 BYTE) ,
  "APPLY_DEPARTMENT" VARCHAR2(100 BYTE) ,
  "BILL_CODE" VARCHAR2(32 BYTE) ,
  "VOUCHER_PERIOD" VARCHAR2(6 BYTE) ,
  "VOUCHER_TAX" VARCHAR2(255 BYTE) ,
  "VOUCHER_DATE" VARCHAR2(8 BYTE) 
)
TABLESPACE "DATA"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "MGJT"."T_SCM_VAT_MAIN_EXTEND"."ACCOUNT_TIME" IS '记账时间';
COMMENT ON COLUMN "MGJT"."T_SCM_VAT_MAIN_EXTEND"."VOUCHER_NUM" IS '凭证号';
COMMENT ON COLUMN "MGJT"."T_SCM_VAT_MAIN_EXTEND"."INV_KIND" IS '发票代码';
COMMENT ON COLUMN "MGJT"."T_SCM_VAT_MAIN_EXTEND"."INV_NUM" IS '发票号码';
COMMENT ON COLUMN "MGJT"."T_SCM_VAT_MAIN_EXTEND"."SYS_COMPANY_CODE" IS '租户id';
COMMENT ON COLUMN "MGJT"."T_SCM_VAT_MAIN_EXTEND"."STATUS" IS '状态';
COMMENT ON COLUMN "MGJT"."T_SCM_VAT_MAIN_EXTEND"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "MGJT"."T_SCM_VAT_MAIN_EXTEND"."TAX_NO" IS '税号';
COMMENT ON COLUMN "MGJT"."T_SCM_VAT_MAIN_EXTEND"."UPDATE_TYPE" IS '更新类型   0 - 插入，1 – 更新，2 - 作废';
COMMENT ON COLUMN "MGJT"."T_SCM_VAT_MAIN_EXTEND"."ACCOUNTTING_NO" IS '报账单号';
COMMENT ON COLUMN "MGJT"."T_SCM_VAT_MAIN_EXTEND"."ACCOUNT_STATUS" IS '报销状态';
COMMENT ON COLUMN "MGJT"."T_SCM_VAT_MAIN_EXTEND"."AMOUNT_USE" IS '使用金额';
COMMENT ON COLUMN "MGJT"."T_SCM_VAT_MAIN_EXTEND"."TAX_USE" IS '使用税额';
COMMENT ON COLUMN "MGJT"."T_SCM_VAT_MAIN_EXTEND"."APPLY_TIME" IS '申请时间';
COMMENT ON COLUMN "MGJT"."T_SCM_VAT_MAIN_EXTEND"."APPLY_NAME" IS '申请人姓名,即:报销人姓名';
COMMENT ON COLUMN "MGJT"."T_SCM_VAT_MAIN_EXTEND"."APPLY_DEPARTMENT" IS '申请人部门';
COMMENT ON COLUMN "MGJT"."T_SCM_VAT_MAIN_EXTEND"."BILL_CODE" IS '单据编号-记账关联单号；外部单据编号';
COMMENT ON COLUMN "MGJT"."T_SCM_VAT_MAIN_EXTEND"."VOUCHER_PERIOD" IS '凭证会计期（YYYYMM）';
COMMENT ON COLUMN "MGJT"."T_SCM_VAT_MAIN_EXTEND"."VOUCHER_TAX" IS '记账税额';
COMMENT ON COLUMN "MGJT"."T_SCM_VAT_MAIN_EXTEND"."VOUCHER_DATE" IS '记账日期（YYYYMMDD）';

-- ----------------------------
-- Checks structure for table T_SCM_VAT_MAIN_EXTEND
-- ----------------------------
ALTER TABLE "MGJT"."T_SCM_VAT_MAIN_EXTEND" ADD CONSTRAINT "SYS_C0018557" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MGJT"."T_SCM_VAT_MAIN_EXTEND" ADD CONSTRAINT "SYS_C0019406" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table T_SCM_VAT_MAIN_EXTEND
-- ----------------------------
CREATE TRIGGER "MGJT"."EXTEND_TRIGGER" BEFORE INSERT ON "MGJT"."T_SCM_VAT_MAIN_EXTEND" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW WHEN (new.ID is null) 
begin
   select extend_sequence.nextval into :new.ID from sys.dual;
end;
/
